version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - customerregister
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      
networks:
  customerregister:
    name: customerregister

volumes:
  mongo:
    driver: local